### ISSUE TITLE
Kaisymbols in Roman

### ISSUE THREAD

**Issue by irenevlachou** [googlefonts/amstelvar-avar2#12]
The construction of kappa and kai-tail isn't really working for most instances, so I redrew them into a single glyph, with the overlaps of kappa and no component parts.
We can delete the lai-tail now from all files and update the glyphConstruction file.
@gferreira should I do it or you prefer you deal with it?

**Comment by gferreira2** [comment]
you can do it :) thanks!

**Comment by irenevlachou** [comment]
done
