### ISSUE TITLE
We need a a build of Amstelvar Roman every day.

### ISSUE THREAD

**Issue by dberlow** [googlefonts/amstelvar-avar2#148]
see previous issue please

**Comment by dberlow** [comment]
also getting different results between Fontra in Typeproof at same designspace location.![Image](https://github.com/user-attachments/assets/5e56e7da-1257-4911-aeb5-1ce3061948ed)

**Comment by sannorozco** [comment]
Yes, we’ll build at the end of every day. There’s a fresh VF just now.
