### ISSUE TITLE
Roman Greek Grade

### ISSUE THREAD

**Issue by dberlow** [googlefonts/amstelvar-avar2#18]
Irene,

I was using the glyphs tool in xtools4 to check the width match of the Roman grade sources.

I found the same couple of dozen Greek glyphs that were out of width synch on both GRAD min and max. 

I corrected by copying the widths, but knew I would also need to "center" the re-spaced glyphs over the default's contour.

First I found this:
![Image](https://github.com/user-attachments/assets/6f1bbd4c-2f23-4049-8103-e1950d98f736)
...and realized there were issues with the contour of the GRAD min.

The purpose of the axis is to allow lightening and darkening of the glyphs for correcting production or output to the original intended weight's appearance.

As such, all contours and composites in the min, must match alignments of the default, but otherwise be _Inside_ the default contour.

Thus, to show a simple example that must be followed, the dieresis tonos must look much more like this:
![Image](https://github.com/user-attachments/assets/a774b8c8-0442-40f3-a733-e165ae43a7d9)

This is from the GRAD max, before:
![Image](https://github.com/user-attachments/assets/11dc5e7b-c8f4-43c8-8df7-2ebd7c1f93bd)
and after:
![Image](https://github.com/user-attachments/assets/fab249c8-973e-4be8-ba3f-d325cb55bff5)

In the grade max, all contours must match the alignments of the default, but otherwise be _Outside_ of the default's contours

The Roman Greek all must be checked for this and my edits.

The Italic Greek GRAD is incomplete.

Let me know if you can check the Roman and complete Italic Greek GRAD.

Cheers, 
David

**Comment by irenevlachou** [comment]
Thank you @dberlow. I'll finish 3 more YTLC Cyrillic so I can close the file and I'll move on to this right after.
